### ISSUE TITLE
Permission prompt keeps popping up

### ISSUE THREAD

**Issue by jfuellert** [phen0menon/awakened-poe-trade#4]
Hey, thank you for putting this together. I've been trying to get this working on my M1 Pro. I've tried running arm64 version (damaged), and universal (works) but have been running into an issue where the permission prompt essentially locks me out of using the app. I've also tried running under Rosetta but same issue occurs.

Here's how I can reproduce the issue:
1. Run the application from the applications folder 
2. The app will then prompt for accessibility permissions
3. Hit allow 
4. Enable the permission in the accessibility settings
5. Re-run the application

Notice the application will continuously show this prompt, regardless of the system settings.

I'd also tried settings other permissions, incase something was mis-labeled. This includes things like disk access, etc. Any help here would be greatly appreciated!

<img width="1192" alt="Screenshot 2023-08-24 at 8 31 55 AM" src="https://github.com/phen0menon/awakened-poe-trade/assets/1046110/ce9e2b8b-1ffc-426e-a793-92e1f1da6654">

**Comment by Illatior** [comment]
same here. also application crashes for me after requesting accessibility permission
<img width="1265" alt="image" src="https://github.com/phen0menon/awakened-poe-trade/assets/55617246/287ec383-112e-4ee7-8059-463a9a5f7a3b">

**Comment by jfuellert** [comment]
I've followed the following steps for the damaged .dmg file in the [guide as outlined](https://www.pathofexile.com/forum/view-thread/3333212) by [phen0menon](https://github.com/phen0menon) and it fixed the issue:

```
sudo xattr -r -d com.apple.quarantine /Applications/Awakened\ PoE\ Trade.app
```

- Remove the directory at /Users/<username>/Library/Application Support/awakened-poe-trade
- Follow the custom build steps
- Allow accessibility manually **before** trying to open the app
- Run `/Applications/Awakened\ PoE\ Trade.app/Contents/MacOS/Awakened\ PoE\ Trade` in terminal
```
